version: "3"
services:
  activemq:
    image: activemq-artemis:latest-alpine
    ports:
      # mqtt
      - "1883:1883"
      # amqp
      - "5672:5672"
      # ui
      - "8161:8161"
      # stomp
      - "61613:61613"
      # ws
      - "61614:61614"
      # jms
      - "61616:61616"
    networks: [ backing-services ]
    volumes: [ "activemq-data:/opt/activemq/conf", "activemq-data:/data/activemq", "activemq-data:/var/log/activemq" ]
    environment:
      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: "true"
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
      ACTIVEMQ_WRITE_LOGIN: write
      ACTIVEMQ_WRITE_PASSWORD: write
      ACTIVEMQ_READ_LOGIN: read
      ACTIVEMQ_READ_PASSWORD: read
      ACTIVEMQ_JMX_LOGIN: jmx
      ACTIVEMQ_JMX_PASSWORD: jmx
      ACTIVEMQ_STATIC_TOPICS: topic-1;topic-2
      ACTIVEMQ_STATIC_QUEUES: queue-1;queue-2
      ACTIVEMQ_ENABLED_SCHEDULER: "true"
      ACTIVEMQ_MIN_MEMORY: 512
      ACTIVEMQ_MAX_MEMORY: 2048

  jdk:
    image: openjdk:17-alpine
    container_name: jdk-17

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: activeMqApp
    ports:
      - 8001:8001
    restart: always
    links:
      - jdk
